model_config:
  base_model: "Qwen/Qwen3-0.6B"
  checkpoint_path: null


n_special_tokens: 3
max_seq_length: 4096

token_config:
  start_sequence_token: "<|im_start|>"
  end_sequence_token: "<|im_end|>"
  start_audio_token: "<|start_of_audio|>"
  end_audio_token: "<|end_of_audio|>"

freeze:
    freeze_emb: False
    freeze_ln: False
    freeze_attn: False
    freeze_ff: False
    freeze_ff_layers: False
      # - 5
      # - 6
      # - 7
      # - 8
      # - 9
      # - 12
      # - 23
      # - 14
      # - 18
      # - 19
      # - 20
      # - 0
      # - 25
    freeze_other: False