raw_data: "urban_flan"
prepared_data_path: "urban_flan_quantized-wav-uni"

path_to_cache: ".."

quantizer_config_path: "../WavTokenizer/configs/wavtokenizer_smalldata_frame40_3s_nq1_code4096_dim512_kmeans200_attn.yaml"
quantizer_ckpt_path: "../audiotokenizer/wavtokenizer_large_unify_600_24k.ckpt"
quantizer_type: "wav"